export const convertObjectParms = (data: any) => {
    const apiParams: any = {
        DealerID: data.DealerID,
        DealerName: data.DealerName?.label,
        StockNo: data.StockNo,
        VIN: data.VIN,
        YearID: data.YearID ?? null,
        Year: data?.Year?.label ?? data?.Year,
        MakeID: data.Make?.value,
        Make: data?.Make?.label,
        ModelID: data.Model?.value,
        Model: data.Model?.label,
        Trim: data.Trim,
        ChromeStyleID: data.ChromeStyleID ?? null,
        ChromeStyle: data.ChromeStyle ?? null,
        BodyId: data.Body?.value,
        Body: data.Body?.label,
        TransID: data.TransName?.value,
        TransName: data.TransName?.label,
        DriveTrainId: data.DriveTrain?.value,
        DriveTrain: data.DriveTrain?.label,
        EngineId: data.Engine?.value,
        Engine: data.Engine?.label,
        ExteriorColorId: data.ExteriorColor?.value,
        ExteriorColor: data.ExteriorColor?.label,
        InteriorColorId: data.InteriorColor?.value,
        InteriorColor: data?.InteriorColor?.label,
        InventoryTypeId: data.InventoryType?.value,
        InventoryType: data.InventoryType?.label,
        OdometerTypeId: data.OdometerType?.value,
        OdometerType: data.OdometerType?.label,
        OdometerReading: data.OdometerReading,
        OEMCertified: data?.OEMCertified?.value ?? null,
        DealerCertified: data?.DealerCertified?.value ?? null,
        RDPrice: data.RDPrice,
        PN_ID: (data?.PN_Name?.value || data.PN_ID) ?? null,
        PN_Name: (data?.PN_Name?.label || data.PN_Name) ?? null,
        IsPrivateNetwork: (data?.PN_Name?.IsPrivateNetwork || data.IsPrivateNetwork) ?? 0,
        Comments: data.Comments,
        CreatedBy: data.CreatedBy ?? null,
        VehiclePhoto: data.VehiclePhoto,
        ModifiedBy: data?.ModifiedBy ?? null
    };
    return apiParams;
};

export const convertoValueObject = (data: any) => {
    const apiParams: any = {
        Inventory_ID: data?.Inventory_ID,
        DealerID: data.DealerID,
        DealerName: { label: data.Dealers?.Name, value: null },
        StockNo: data.StockNo,
        VIN: data.VIN,
        Year: { label: data.Year, value: data.YearID ?? null },
        Make: { label: data?.Make, value: data.MakeID },
        Model: { label: data.Model, value: data.ModelID },
        Trim: data.Trim,
        ChromeStyleID: data.ChromeStyleID ?? null,
        ChromeStyle: data.ChromeStyle ?? null,
        Body: { label: data.Body, value: data.BodyId },
        TransName: { label: data.TransName, value: data.TransID },
        DriveTrain: { label: data.DriveTrain, value: data.DriveTrainId },
        Engine: { label: data.Engine, value: data.EngineId },
        ExteriorColor: data.ExteriorColor || data.ExteriorColorId ? { label: data.ExteriorColor || "", value: data.ExteriorColorId || null } : null,
        InteriorColor: { label: data?.InteriorColor ?? "", value: data.InteriorColorId ?? null } ?? null,
        InventoryType: data.InventoryType || data.InventoryTypeId ? { label: data.InventoryType || "", value: data.InventoryTypeId || null } : null,
        OdometerType: data.OdometerType || data.OdometerTypeId ? { label: data.OdometerType || "", value: data.OdometerTypeId || "" } : null,
        OdometerReading: data.OdometerReading,
        OEMCertified: data.OEMCertified !== null ? { label: data.OEMCertified === 1 ? "Yes" : "No", value: data?.OEMCertified } : null,
        DealerCertified: data.DealerCertified !== null ? { label: data.DealerCertified === 1 ? "Yes" : "No", value: data.DealerCertified } : null,
        RDPrice: data.RDPrice,
        Comments: data.Comments,
        ModifiedBy: data.ModifiedBy,
        VehiclePhoto: data.VehiclePhoto,
        PN_ID: data.PN_ID,
        PN_Name: data.PN_Name,
        IsPrivateNetwork: data.IsPrivateNetwork
    };
    return apiParams;
};
