export const DealersFormConfig = [
    {
        Label: "",
        Required: true,
        Name: "Name",
        InitialValue: "",
        Regex: [],
        RegExError: "Please enter Dealer Name",
        ErrorMessage: "Dealer Name is required*",
        Tooltip: "Dealer Name",
        HelperText: "",
        Type: "text",
        List: null,
        Categery: "Dealer_Form",
        Group: "Dealer_Details",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        Header: "Dealer Name",
        PlaceHolder: "",
        Disabled: false
    },
    {
        Label: "",
        Required: false,
        Name: "ContactName",
        InitialValue: "",
        Regex: ["^[A-Za-z ]+$"],
        RegExError: "Please enter Contact Name",
        ErrorMessage: "Contact Name is required*",
        Tooltip: "Contact Name",
        HelperText: "",
        Type: "text",
        List: null,
        Categery: "Dealer_Form",
        Group: "Dealer_Details",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        Header: "Contact Name",
        PlaceHolder: "e.g John Doe",
        Disabled: false
    },
    {
        Label: "",
        Required: true,
        Name: "Email",
        InitialValue: "",
        Regex: ["^[a-zA-Z0-9._%+-]+@([a-zA-Z0-9.-]+\\.)+[a-zA-Z]{2,7}$"],
        RegExError: "Please enter Email",
        ErrorMessage: "Email is required*",
        Tooltip: "Email",
        HelperText: "",
        Type: "text",
        List: null,
        Categery: "Dealer_Form",
        Group: "Dealer_Details",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        Header: "Email",
        PlaceHolder: "e.g johndoe@gmail.com",
        Disabled: false
    },
    {
        Label: "",
        Required: false,
        Name: "BillingEmail",
        InitialValue: "",
        Regex: ["^[a-zA-Z0-9._%+-]+@([a-zA-Z0-9.-]+\\.)+[a-zA-Z]{2,7}$"],
        RegExError: "Please enter Billing Email",
        ErrorMessage: "Billing Email is required*",
        Tooltip: "Billing Email",
        HelperText: "",
        Type: "text",
        List: null,
        Categery: "Dealer_Form",
        Group: "Dealer_Details",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        Header: "Billing Email",
        PlaceHolder: "e.g johndoe@yahoo.com",
        Disabled: false
    },
    {
        Label: "",
        Required: true,
        Name: "PhoneNo",
        InitialValue: "",
        Regex: ["^\\s*\\d{10}\\s*$"],
        RegExError: "Please enter Telephone Number",
        ErrorMessage: "Telephone Number is required*",
        Tooltip: "Telephone Number",
        HelperText: "",
        Type: "phoneNumber",
        List: null,
        Categery: "Dealer_Form",
        Group: "Dealer_Details",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        Header: "Telephone",
        PlaceHolder: "e.g (123) 456-7890",
        Disabled: false
    },
    {
        Label: "",
        Required: false,
        Name: "SecondaryPhoneNo",
        InitialValue: "",
        Regex: ["^\\s*\\d{10}\\s*$"],
        RegExError: "Please enter Secondary Telephone",
        ErrorMessage: "Secondary Telephone is required*",
        Tooltip: "Secondary Telephone",
        HelperText: "",
        Type: "phoneNumber",
        List: null,
        Categery: "Dealer_Form",
        Group: "Dealer_Details",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        Header: "Secondary Telephone",
        PlaceHolder: "e.g (123) 456-7890",
        Disabled: false
    },
    {
        Label: "",
        Required: false,
        Name: "Fax",
        InitialValue: "",
        Regex: [],
        RegExError: "Please enter Fax",
        ErrorMessage: "Fax is required*",
        Tooltip: "Fax",
        HelperText: "",
        Type: "text",
        List: null,
        Categery: "Dealer_Form",
        Group: "Dealer_Details",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        Header: "Fax",
        PlaceHolder: "e.g 123-456-7890",
        Disabled: false
    },
    {
        Label: "",
        Required: false,
        Name: "WebsiteURL",
        InitialValue: "",
        Regex: [],
        RegExError: "Please enter Website URL",
        ErrorMessage: "Website URL is required*",
        Tooltip: "Website URL",
        HelperText: "",
        Type: "text",
        List: null,
        Categery: "Dealer_Form",
        Group: "Dealer_Details",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        Header: "Website URL",
        PlaceHolder: "e.g https://website.com",
        Disabled: false
    },
    {
        Label: "Active",
        Required: true,
        Name: "IsDealerActive",
        InitialValue: "",
        Regex: [],
        RegExError: "",
        ErrorMessage: "Status is required*",
        Tooltip: "",
        HelperText: "",
        Type: "switch",
        List: null,
        Categery: "Dealer_Form",
        Group: "Dealer_Details",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        Header: "Status",
        PlaceHolder: "",
        Disabled: false
    }
];

export const DealersLocationConfig = [
    {
        Label: "",
        Required: true,
        Name: "Country",
        InitialValue: "",
        Regex: [],
        RegExError: "Please enter Country",
        ErrorMessage: "Dealer Country is required*",
        Tooltip: "Dealer Country",
        HelperText: "",
        Type: "select",
        List: [
            { label: "United States", value: "US" },
            { label: "Canada", value: "CA" }
        ],
        Categery: "Dealer_Form",
        Group: "Location_Details",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        Header: "Country",
        PlaceHolder: "Please Select Country",
        Disabled: false
    },
    {
        Label: "",
        Required: true,
        Name: "State",
        InitialValue: "",
        Regex: [],
        RegExError: "Please enter State/Province",
        ErrorMessage: "State/Province is required*",
        Tooltip: "State/Province",
        HelperText: "",
        Type: "select",
        List: null,
        Categery: "USState",
        Group: "Location_Details",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        Header: "State/Province",
        PlaceHolder: "Please Select State",
        Disabled: false
    },
    {
        Label: "",
        Required: false,
        Name: "City",
        InitialValue: "",
        Regex: [],
        RegExError: "Please enter City",
        ErrorMessage: "City is required*",
        Tooltip: "City",
        HelperText: "",
        Type: "text",
        List: null,
        Categery: "Dealer_Form",
        Group: "Location_Details",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        Header: "City",
        PlaceHolder: "City",
        Disabled: false
    },
    {
        Label: "",
        Required: false,
        Name: "Address_1",
        InitialValue: "",
        Regex: [],
        RegExError: "Please enter Address",
        ErrorMessage: "Address is required*",
        Tooltip: "Address",
        HelperText: "",
        Type: "text",
        List: null,
        Categery: "Dealer_Form",
        Group: "Location_Details",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        Header: "Address",
        PlaceHolder: "Address",
        Disabled: false
    },
    {
        Label: "",
        Required: false,
        Name: "Address_2",
        InitialValue: "",
        Regex: [],
        RegExError: "Please enter Address2",
        ErrorMessage: "Address2 is required*",
        Tooltip: "Address2",
        HelperText: "",
        Type: "text",
        List: null,
        Categery: "Dealer_Form",
        Group: "Location_Details",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        Header: "Address 2",
        PlaceHolder: "Address 2",
        Disabled: false
    },
    {
        Label: "",
        Required: true,
        Name: "TimeZone",
        InitialValue: "",
        Regex: [],
        RegExError: "Please enter Time Zone",
        ErrorMessage: "Time Zone is required*",
        Tooltip: "Time Zone",
        HelperText: "",
        Type: "select",
        List: null,
        Categery: "Dealer_Form",
        Group: "Location_Details",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        Header: "Time Zone",
        PlaceHolder: "TimeZone",
        Disabled: false
    },
    {
        Label: "",
        Required: false,
        Name: "Zipcode",
        InitialValue: "",
        Regex: ["^\\s*\\d{5}\\s*$"],
        RegExError: "Please enter Zip Code",
        ErrorMessage: "Zip Code is required*",
        Tooltip: "Zip Code",
        HelperText: "",
        Type: "number",
        List: null,
        Categery: "Dealer_Form",
        Group: "Location_Details",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        Header: "Zip Code",
        PlaceHolder: "Zip code",
        Disabled: false
    },
    {
        Label: "",
        Required: false,
        Name: "GeoLocation",
        InitialValue: "",
        Regex: [],
        RegExError: "Please enter GEO Location",
        ErrorMessage: "GEO Location is required*",
        Tooltip: "GEO Location",
        HelperText: "",
        Type: "text",
        List: null,
        Categery: "Dealer_Form",
        Group: "Location_Details",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        Header: "GEO Location",
        PlaceHolder: "GEO Location",
        Disabled: false
    }
];

export const InventorySettingsConfig = [
    {
        Label: "",
        Required: false,
        Name: "InventoryStatus",
        InitialValue: "Not Listed",
        Regex: [],
        RegExError: "",
        ErrorMessage: "InventoryStatus is required*",
        Tooltip: "Inventory Status",
        HelperText: "",
        Type: "text",
        List: null,
        Categery: "Dealer_Form",
        Group: "Dealer_Details",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        Header: "Inventory Status",
        PlaceHolder: "Inventory Status",
        Disabled: true
    },
    {
        Label: "",
        Required: false,
        Name: "AutoListDays",
        InitialValue: 1,
        Regex: [],
        RegExError: "Please enter Auto List inventory when # days in stock is over",
        ErrorMessage: "Auto List Inventory is required*",
        Tooltip: "Auto List inventory when # days in stock is over",
        HelperText: "",
        Type: "text",
        List: null,
        Categery: "Dealer_Form",
        Group: "Dealer_Details",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        Header: "Auto List inventory when # days in stock is over",
        PlaceHolder: "Auto List inventory when # days in stock is over",
        Disabled: false
    },
    {
        Label: "Price Option for Auto List",
        Required: false,
        Name: "PriceOption",
        InitialValue: "usePriceInInventory",
        Regex: [],
        RegExError: "",
        ErrorMessage: "",
        Tooltip: "Price Option for Auto List",
        HelperText: "",
        Type: "radio",
        List: [
            {
                label: "Use price provided in inventory feed",
                value: "usePriceInInventory"
            }
        ],
        Categery: "Dealer_Form",
        Group: "Dealer_Details",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        Header: "Price Option for Auto List",
        PlaceHolder: "",
        Disabled: false
    },
    {
        Label: "",
        Required: false,
        Name: "Cutoff_Days",
        InitialValue: "",
        Regex: [],
        RegExError: "Please enter CutOff Days",
        ErrorMessage: "CutOff Days is required*",
        Tooltip: "CutOff Days",
        HelperText: "",
        Type: "text",
        List: null,
        Categery: "Dealer_Form",
        Group: "Dealer_Details",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        Header: "CutOff Days",
        PlaceHolder: "0",
        Disabled: false
    },
    {
        Label: "Email the store's main contact when inventory is updated via the auto-list settings",
        Required: false,
        Name: "AutoDelistEmail",
        InitialValue: false,
        Regex: [],
        RegExError: "",
        ErrorMessage: "",
        Tooltip: "Email the store's main contact when inventory is updated via the auto-list settings",
        HelperText: "",
        Type: "checkbox",
        List: null,
        Categery: "Dealer_Form",
        Group: "Dealer_Details",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        Header: "Auto-Delist Email Notification",
        PlaceHolder: "",
        Disabled: false
    },
    {
        Label: "Emails the store's main contact when inventory is auto-de-listed",
        Required: false,
        Name: "AutoDelistEmail_2",
        InitialValue: false,
        Regex: [],
        RegExError: "",
        ErrorMessage: "",
        Tooltip: "Emails the store's main contact when inventory is auto-de-listed",
        HelperText: "",
        Type: "checkbox",
        List: null,
        Categery: "Dealer_Form",
        Group: "Dealer_Details",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        Header: "Auto-Delist Email Notification",
        PlaceHolder: "",
        Disabled: false
    },
    {
        Label: "",
        Required: false,
        Name: "DataFeedID",
        InitialValue: "",
        Regex: [],
        RegExError: "Please enter Data Feed ID",
        ErrorMessage: "Data Feed IDy is required*",
        Tooltip: "Data Feed ID",
        HelperText: "",
        Type: "text",
        List: null,
        Categery: "Dealer_Form",
        Group: "Dealer_Details",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        Header: "Data Feed ID",
        PlaceHolder: "Data Feed ID",
        Disabled: false
    },
    {
        Label: "",
        Required: false,
        Name: "APIToken",
        InitialValue: "",
        Regex: [],
        RegExError: "Please enter API Token",
        ErrorMessage: "API Token is required*",
        Tooltip: "API Token",
        HelperText: "",
        Type: "text",
        List: null,
        Categery: "Dealer_Form",
        Group: "Dealer_Details",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        Header: "API Token",
        PlaceHolder: "API Token",
        Disabled: false
    },
    {
        Label: "",
        Required: false,
        Name: "CarFaxID",
        InitialValue: "",
        Regex: [],
        RegExError: "Please enter CarFax Partner ID",
        ErrorMessage: "CarFax Partner ID is required*",
        Tooltip: "CarFax Partner ID",
        HelperText: "",
        Type: "text",
        List: null,
        Categery: "Dealer_Form",
        Group: "Dealer_Details",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        Header: "CarFax Partner ID",
        PlaceHolder: "CarFax Partner ID",
        Disabled: false
    },
    {
        Label: "",
        Required: false,
        Name: "AutoCheckID",
        InitialValue: "",
        Regex: [],
        RegExError: "Please enter AutoCheck Partner ID",
        ErrorMessage: "AutoCheck Partner ID is required*",
        Tooltip: "AutoCheck Partner ID",
        HelperText: "",
        Type: "text",
        List: null,
        Categery: "Dealer_Form",
        Group: "Dealer_Details",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        Header: "AutoCheck Partner ID",
        PlaceHolder: "AutoCheck Partner ID",
        Disabled: false
    },
    {
        Label: "",
        Required: false,
        Name: "PN_Name",
        InitialValue: "",
        Regex: [],
        RegExError: "Please enter Name",
        ErrorMessage: "Role is required*",
        Tooltip: "Parent Dealership Name",
        HelperText: "",
        Type: "select",
        List: null,
        Categery: "Dealer_Form",
        Group: "Dealer_Details",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        Header: "Select Parent Dealership Name",
        PlaceHolder: "Select Parent Dealership Name",
        Disabled: false
    }
];
export const InventoryListSettingsConfig = [
    {
        Label: "",
        Required: false,
        Name: "InventoryStatus",
        InitialValue: "Not Listed",
        Regex: [],
        RegExError: "",
        ErrorMessage: "InventoryStatus is required*",
        Tooltip: "InventoryStatus",
        HelperText: "",
        Type: "text",
        List: null,
        Categery: "Dealer_Form",
        Group: "Dealer_Details",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        Header: "Inventory Status",
        PlaceHolder: "",
        Disabled: true
    },
    {
        Label: "",
        Required: false,
        Name: "Cutoff_Days",
        InitialValue: "",
        Regex: [],
        RegExError: "Please enter CutOff Days",
        ErrorMessage: "CutOff Days is required*",
        Tooltip: "CutOff Days",
        HelperText: "",
        Type: "text",
        List: null,
        Categery: "Dealer_Form",
        Group: "Dealer_Details",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        Header: "CutOff Days",
        PlaceHolder: "CutOff Days",
        Disabled: false
    },
    {
        Label: "Emails the store's main contact when inventory is auto-de-listed",
        Required: false,
        Name: "AutoDelistEmail_2",
        InitialValue: false,
        Regex: [],
        RegExError: "",
        ErrorMessage: "",
        Tooltip: "Emails the store's main contact when inventory is auto-de-listed",
        HelperText: "",
        Type: "checkbox",
        List: null,
        Categery: "Dealer_Form",
        Group: "Dealer_Details",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        Header: "Auto-Delist Email Notification",
        PlaceHolder: "",
        Disabled: false
    },
    {
        Label: "",
        Required: true,
        Name: "CarFaxID",
        InitialValue: "",
        Regex: [],
        RegExError: "Please enter CarFax Partner ID",
        ErrorMessage: "CarFax Partner ID is required*",
        Tooltip: "CarFax Partner ID",
        HelperText: "",
        Type: "text",
        List: null,
        Categery: "Dealer_Form",
        Group: "Dealer_Details",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        Header: "CarFax Partner ID",
        PlaceHolder: "",
        Disabled: false
    },
    {
        Label: "",
        Required: true,
        Name: "AutoCheckID",
        InitialValue: "",
        Regex: [],
        RegExError: "Please enter AutoCheck Partner ID",
        ErrorMessage: "AutoCheck Partner ID is required*",
        Tooltip: "AutoCheck Partner ID",
        HelperText: "",
        Type: "text",
        List: null,
        Categery: "Dealer_Form",
        Group: "Dealer_Details",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        Header: "AutoCheck Partner ID",
        PlaceHolder: "",
        Disabled: false
    },
    {
        Label: "",
        Required: false,
        Name: "PN_Name",
        InitialValue: "",
        Regex: [],
        RegExError: "Please enter Name",
        ErrorMessage: "Role is required*",
        Tooltip: "Parent Dealership Name",
        HelperText: "",
        Type: "select",
        List: null,
        Categery: "Dealer_Form",
        Group: "Dealer_Details",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        Header: "Select Parent Dealership",
        PlaceHolder: "Select Parent Dealership",
        Disabled: false
    }
];

export const DealersUserDetailsConfig = [
    {
        Label: "",
        Required: true,
        Name: "RoleName",
        InitialValue: "",
        Regex: [],
        RegExError: "Please enter Name",
        ErrorMessage: "Role is required*",
        Tooltip: "Role Name",
        HelperText: "",
        Type: "select",
        List: null,
        Categery: "Dealer_Form",
        Group: "Dealer_Details",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        Header: "Select Role",
        PlaceHolder: "Select Role",
        Disabled: false
    },
    {
        Label: "",
        Required: true,
        Name: "First_Name",
        InitialValue: "",
        Regex: ["^[A-Za-z ]+$"],
        RegExError: "Please enter First Name",
        ErrorMessage: "First Name is required*",
        Tooltip: "First Name",
        HelperText: "",
        Type: "text",
        List: null,
        Categery: "Dealer_Form",
        Group: "Dealer_Details",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        Header: "First Name",
        PlaceHolder: "e.g john",
        Disabled: false
    },
    {
        Label: "",
        Required: true,
        Name: "Last_Name",
        InitialValue: "",
        Regex: ["^[A-Za-z ]+$"],
        RegExError: "Please enter Last Name",
        ErrorMessage: "Last Name is required*",
        Tooltip: "Last Name",
        HelperText: "",
        Type: "text",
        List: null,
        Categery: "Dealer_Form",
        Group: "Dealer_Details",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        Header: "Last Name",
        PlaceHolder: "e.g doe",
        Disabled: false
    },
    {
        Label: "",
        Required: true,
        Name: "Phone_No",
        InitialValue: "",
        Regex: ["^\\s*\\d{10}\\s*$"],
        RegExError: "Please enter Phone Number",
        ErrorMessage: "Phone Number is required*",
        Tooltip: "Phone Number",
        HelperText: "",
        Type: "phoneNumber",
        List: null,
        Categery: "Dealer_Form",
        Group: "Dealer_Details",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        Header: "Phone Number",
        PlaceHolder: "e.g (123) 456-7890 ",
        Disabled: false
    },
    {
        Label: "",
        Required: true,
        Name: "Email",
        InitialValue: "",
        Regex: ["^[a-zA-Z0-9._%+-]+@([a-zA-Z0-9.-]+\\.)+[a-zA-Z]{2,7}$"],
        RegExError: "Please enter Email",
        ErrorMessage: "Email is required*",
        Tooltip: "Email",
        HelperText: "",
        Type: "text",
        List: null,
        Categery: "Dealer_Form",
        Group: "Dealer_Details",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        Header: "Email",
        PlaceHolder: "e.g johndoe@gmail.com",
        Disabled: false
    },
    {
        Label: "Active",
        Required: true,
        Name: "IsActive",
        InitialValue: "",
        Regex: [],
        RegExError: "",
        ErrorMessage: "Status is required*",
        Tooltip: "Status",
        HelperText: "",
        Type: "switch",
        List: null,
        Categery: "Dealer_Form",
        Group: "Dealer_Details",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        Header: "Status",
        PlaceHolder: "",
        Disabled: false
    }
];
