export const ContactUsConfig = [
    {
        Label: "First Name",
        Required: true,
        Name: "FirstName",
        InitialValue: "",
        Regex: [],
        RegExError: "Please enter First Name",
        ErrorMessage: "First Name is required*",
        Tooltip: "First Name",
        HelperText: "",
        Type: "text",
        List: null,
        Categery: "Generate Page",
        Group: "Report_Data",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        PlaceHolder: "",
        Disabled: false
    },
    {
        Label: "Last Name",
        Required: true,
        Name: "LastName",
        InitialValue: "",
        Regex: [],
        RegExError: "Please enter Last Name",
        ErrorMessage: "Last Name is required*",
        Tooltip: "Last Name",
        HelperText: "",
        Type: "text",
        List: null,
        Categery: "Generate Page",
        Group: "Report_Data",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        PlaceHolder: "",
        Disabled: false
    },
    {
        Label: "Email",
        Required: true,
        Name: "Email",
        InitialValue: "",
        Regex: [],
        RegExError: "Please enter Email",
        ErrorMessage: "Email is required*",
        Tooltip: "Email",
        HelperText: "",
        Type: "text",
        List: null,
        Categery: "Generate Page",
        Group: "Report_Data",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        PlaceHolder: "",
        Disabled: false
    },
    {
        Label: "Phone Number",
        Required: true,
        Name: "PhoneNumber",
        InitialValue: "",
        Regex: ["^\\s*\\d{10}\\s*$"],
        RegExError: "Please enter Phone Number",
        ErrorMessage: "Phone Number is required*",
        Tooltip: "Phone Number",
        HelperText: "",
        Type: "number",
        List: null,
        Categery: "Generate Page",
        Group: "Report_Data",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        PlaceHolder: "",
        Disabled: false
    },
    {
        Label: "Dealership",
        Required: true,
        Name: "Dealership",
        InitialValue: "",
        Regex: [],
        RegExError: "Please enter Dealership",
        ErrorMessage: "Dealership is required*",
        Tooltip: "Dealership",
        HelperText: "",
        Type: "text",
        List: null,
        Categery: "Generate Page",
        Group: "Report_Data",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        PlaceHolder: "",
        Disabled: false
    },
    {
        Label: "Message",
        Required: true,
        Name: "Message",
        InitialValue: "",
        Regex: [],
        RegExError: "Please enter Message",
        ErrorMessage: "Message is required*",
        Tooltip: "Message",
        HelperText: "",
        Type: "TextArea",
        List: null,
        Categery: "Generate Page",
        Group: "Report_Data",
        MinValue: null,
        MaxValue: null,
        Multiple: 0,
        PlaceHolder: "",
        Disabled: false,
        rows: 2
    }
];
